/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-14 00:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertProducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

	String sessionId=(String)session.getAttribute("id");
	String sessionRole=(String)session.getAttribute("role");
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>제품등록</title>\r\n");
      out.write("<style>\r\n");
      out.write("	div {\r\n");
      out.write("		width : 700px;\r\n");
      out.write("		margin: 0 auto ; \r\n");
      out.write("	}\r\n");
      out.write("	td {\r\n");
      out.write("		padding: 10px; \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<center>\r\n");
      out.write("		<h1> 제품 등록 페이지 (관리자만 접근가능.)</h1>\r\n");
      out.write("		<hr> \r\n");
      out.write("		");
 
		
			if (sessionRole != null && sessionRole.equals("Admin")){
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"logout.do\">Log-out</a>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<form action=\"insertProducts.do\" method=\"post\">\r\n");
      out.write("			<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">코드</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_code\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">이름</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_name\" size=\"10\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">종류</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_kind\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">가격</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_price\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">상세 정보</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_content\" cols=\"40\" rows=\"10\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				<td bgcolor=\"green\" width=\"70\">수량</td>\r\n");
      out.write("				<td align=\"left\"><input type=\"text\" name=\"p_quantity\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("						value=\" 새 제품 등록 \" /></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		");

			}else{		//sessionId변수가 null 일떄 출력 부분
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			당신은 로그인 되지 않는 상태입니다. 먼저 로그인후 글을 쓸 수 있습니다.\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<a href=\"LoginForm.jsp\">로그인 하기</a>\r\n");
      out.write("		\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
